/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#b8cf84",
        "surface-variant": "#e5e2e1",
        "primary-container": "#4b5e20",
        "tertiary": "#394516",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b7d257",
        "tertiary-container": "#505d2b",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#c5d597",
        "on-secondary-fixed-variant": "#3e4c00",
        "surface-container-low": "#f6f3f2",
        "on-primary-fixed": "#141f00",
        "error": "#ba1a1a",
        "background": "#fcf9f8",
        "surface-container": "#f0eded",
        "primary-fixed": "#d4ec9e",
        "on-tertiary-fixed": "#161f00",
        "surface-tint": "#526526",
        "on-tertiary-fixed-variant": "#3f4c1b",
        "outline-variant": "#c6c8b8",
        "primary-fixed-dim": "#b8cf84",
        "tertiary-fixed": "#daeaa9",
        "on-surface-variant": "#45483c",
        "surface-dim": "#dcd9d9",
        "primary": "#344609",
        "secondary-fixed": "#d3ee6f",
        "surface-bright": "#fcf9f8",
        "outline": "#76786a",
        "on-primary-container": "#c0d78b",
        "on-surface": "#1c1b1b",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-fixed": "#171e00",
        "on-background": "#1c1b1b",
        "tertiary-fixed-dim": "#becd90",
        "inverse-surface": "#313030",
        "on-secondary": "#ffffff",
        "secondary-container": "#d0eb6d",
        "on-primary-fixed-variant": "#3b4d10",
        "surface": "#fcf9f8",
        "secondary": "#536600",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-high": "#eae7e7",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#576a00",
        "inverse-on-surface": "#f3f0ef"
      },
      borderRadius: {
        DEFAULT: "0.25rem", // Found 0.25rem in the first html, 0.5rem in second. 
        sm: "0.25rem",
        md: "0.5rem", // Usually 0.5rem is md
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        xxl: "80px",
        gutter: "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        display: ["Newsreader", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "headline-sm": ["Newsreader", "serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Newsreader", "serif"],
        "display-lg": ["Newsreader", "serif"],
        "label-md": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "body-lg": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
